- Target: openaf/ojobrt:nightly (alpine 3.20.3)
  Class: os-pkgs
  Type: alpine
- Target: Java
  Class: lang-pkgs
  Type: jar
  Vulnerabilities:
  - VulnerabilityID: CVE-2024-6763
    PkgName: org.eclipse.jetty:jetty-http
    PkgPath: openaf/openaf.jar
    PkgIdentifier:
      PURL: pkg:maven/org.eclipse.jetty/jetty-http@9.4.56.v20240826
      UID: 16a78109ae818b93
    InstalledVersion: 9.4.56.v20240826
    FixedVersion: 12.0.12
    Status: fixed
    Layer:
      Digest: sha256:0128b2c74739c5005e95542802c7e75dccd7d6f79e6c28eccfccc253499b1f19
      DiffID: sha256:e06a1f9d220ef92a54414c6e52fb3732656d59a478948fe01f0392f19cfde5f4
    SeveritySource: ghsa
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2024-6763
    DataSource:
      ID: ghsa
      Name: GitHub Security Advisory Maven
      URL: https://github.com/advisories?query=type%3Areviewed+ecosystem%3Amaven
    Title: 'org.eclipse.jetty:jetty-http: jetty: Jetty URI parsing of invalid authority'
    Description: |-
      Eclipse Jetty is a lightweight, highly scalable, Java-based web server and Servlet engine . It includes a utility class, HttpURI, for URI/URL parsing.

      The HttpURI class does insufficient validation on the authority segment of a URI.  However the behaviour of HttpURI
       differs from the common browsers in how it handles a URI that would be 
      considered invalid if fully validated against the RRC.  Specifically HttpURI
       and the browser may differ on the value of the host extracted from an 
      invalid URI and thus a combination of Jetty and a vulnerable browser may
       be vulnerable to a open redirect attack or to a SSRF attack if the URI 
      is used after passing validation checks.
    Severity: LOW
    CweIDs:
    - CWE-1286
    VendorSeverity:
      ghsa: 1
      redhat: 1
    CVSS:
      ghsa:
        V3Vector: CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:L/A:N
        V3Score: 3.7
      redhat:
        V3Vector: CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:L/A:N
        V3Score: 3.7
    References:
    - https://access.redhat.com/security/cve/CVE-2024-6763
    - https://github.com/jetty/jetty.project
    - https://github.com/jetty/jetty.project/pull/12012
    - https://github.com/jetty/jetty.project/security/advisories/GHSA-qh8g-58pp-2wxh
    - https://gitlab.eclipse.org/security/cve-assignement/-/issues/25
    - https://nvd.nist.gov/vuln/detail/CVE-2024-6763
    - https://www.cve.org/CVERecord?id=CVE-2024-6763
    PublishedDate: '2024-10-14T16:15:04.163Z'
    LastModifiedDate: '2024-10-15T12:57:46.88Z'
