- Target: openaf/ojobrt:8-latest (alpine 3.19.1)
  Class: os-pkgs
  Type: alpine
  Vulnerabilities:
  - VulnerabilityID: CVE-2023-52425
    PkgID: libexpat@2.5.0-r2
    PkgName: libexpat
    PkgIdentifier:
      PURL: pkg:apk/alpine/libexpat@2.5.0-r2?arch=x86_64&distro=3.19.1
    InstalledVersion: 2.5.0-r2
    FixedVersion: 2.6.0-r0
    Status: fixed
    Layer:
      Digest: sha256:4187a72d2352f9c12622e658a46bc6717599cfd3a97e860b7828667284496ba9
      DiffID: sha256:f96fbd518ff89691dd5e7df2e5032406cfca7b044caa33e5fe66e1b86b72684f
    SeveritySource: nvd
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2023-52425
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'expat: parsing large tokens can trigger a denial of service'
    Description: libexpat through 2.5.0 allows a denial of service (resource consumption) because many full reparsings are required in the case of a large token for which multiple buffer fills are needed.
    Severity: HIGH
    CweIDs:
    - CWE-400
    VendorSeverity:
      nvd: 3
      redhat: 2
    CVSS:
      nvd:
        V3Vector: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H
        V3Score: 7.5
      redhat:
        V3Vector: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L
        V3Score: 5.3
    References:
    - https://access.redhat.com/security/cve/CVE-2023-52425
    - https://github.com/libexpat/libexpat/pull/789
    - https://nvd.nist.gov/vuln/detail/CVE-2023-52425
    - https://www.cve.org/CVERecord?id=CVE-2023-52425
    PublishedDate: '2024-02-04T20:15:46.063Z'
    LastModifiedDate: '2024-02-09T02:03:16.3Z'
  - VulnerabilityID: CVE-2023-52426
    PkgID: libexpat@2.5.0-r2
    PkgName: libexpat
    PkgIdentifier:
      PURL: pkg:apk/alpine/libexpat@2.5.0-r2?arch=x86_64&distro=3.19.1
    InstalledVersion: 2.5.0-r2
    FixedVersion: 2.6.0-r0
    Status: fixed
    Layer:
      Digest: sha256:4187a72d2352f9c12622e658a46bc6717599cfd3a97e860b7828667284496ba9
      DiffID: sha256:f96fbd518ff89691dd5e7df2e5032406cfca7b044caa33e5fe66e1b86b72684f
    SeveritySource: nvd
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2023-52426
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'expat: recursive XML entity expansion vulnerability'
    Description: libexpat through 2.5.0 allows recursive XML Entity Expansion if XML_DTD is undefined at compile time.
    Severity: MEDIUM
    CweIDs:
    - CWE-776
    VendorSeverity:
      nvd: 2
      redhat: 2
      ubuntu: 2
    CVSS:
      nvd:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H
        V3Score: 5.5
      redhat:
        V3Vector: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L
        V3Score: 5.3
    References:
    - https://access.redhat.com/security/cve/CVE-2023-52426
    - https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-52426
    - https://cwe.mitre.org/data/definitions/776.html
    - https://github.com/libexpat/libexpat/commit/0f075ec8ecb5e43f8fdca5182f8cca4703da0404
    - https://github.com/libexpat/libexpat/pull/777
    - https://nvd.nist.gov/vuln/detail/CVE-2023-52426
    - https://www.cve.org/CVERecord?id=CVE-2023-52426
    PublishedDate: '2024-02-04T20:15:46.12Z'
    LastModifiedDate: '2024-02-09T02:02:39.8Z'
