- Target: openaf/ojobrt:nightly (alpine 3.18.4)
  Class: os-pkgs
  Type: alpine
- Target: Java
  Class: lang-pkgs
  Type: jar
  Vulnerabilities:
  - VulnerabilityID: CVE-2023-36478
    PkgName: org.eclipse.jetty:jetty-http
    PkgPath: openaf/openaf.jar
    InstalledVersion: 9.4.52.v20230823
    FixedVersion: 10.0.16, 11.0.16, 9.4.53
    Status: fixed
    Layer:
      Digest: sha256:4e48f17ecb627610c97b487ca6fbfd2c834289f2f3749b109d5a95190d98da5d
      DiffID: sha256:78d6de20ed4a2d075d83e84360b2b884d931c4c10ba9fdfd295915e04474dd21
    SeveritySource: ghsa
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2023-36478
    DataSource:
      ID: ghsa
      Name: GitHub Security Advisory Maven
      URL: https://github.com/advisories?query=type%3Areviewed+ecosystem%3Amaven
    Title: hpack header values cause
    Description: |-
      Eclipse Jetty provides a web server and servlet container. In versions 11.0.0 through 11.0.15, 10.0.0 through 10.0.15, and 9.0.0 through 9.4.52, an integer overflow in `MetaDataBuilder.checkSize` allows for HTTP/2 HPACK header values to
      exceed their size limit. `MetaDataBuilder.java` determines if a header name or value exceeds the size limit, and throws an exception if the limit is exceeded. However, when length is very large and huffman is true, the multiplication by 4 in line 295
      will overflow, and length will become negative. `(_size+length)` will now be negative, and the check on line 296 will not be triggered. Furthermore, `MetaDataBuilder.checkSize` allows for user-entered HPACK header value sizes to be negative, potentially leading to a very large buffer allocation later on when the user-entered size is multiplied by 2. This means that if a user provides a negative length value (or, more precisely, a length value which, when multiplied by the 4/3 fudge factor, is negative), and this length value is a very large positive number when multiplied by 2, then the user can cause a very large buffer to be allocated on the server. Users of HTTP/2 can be impacted by a remote denial of service attack. The issue has been fixed in versions 11.0.16, 10.0.16, and 9.4.53. There are no known workarounds.
    Severity: HIGH
    CweIDs:
    - CWE-190
    - CWE-400
    CVSS:
      ghsa:
        V3Vector: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H
        V3Score: 7.5
      redhat:
        V3Vector: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H
        V3Score: 7.5
    References:
    - https://access.redhat.com/security/cve/CVE-2023-36478
    - https://github.com/eclipse/jetty.project
    - https://github.com/eclipse/jetty.project/pull/9634
    - https://github.com/eclipse/jetty.project/releases/tag/jetty-10.0.16
    - https://github.com/eclipse/jetty.project/releases/tag/jetty-11.0.16
    - https://github.com/eclipse/jetty.project/releases/tag/jetty-9.4.53.v20231009
    - https://github.com/eclipse/jetty.project/security/advisories/GHSA-wgh7-54f2-x98r
    - https://nvd.nist.gov/vuln/detail/CVE-2023-36478
    - https://www.cve.org/CVERecord?id=CVE-2023-36478
    PublishedDate: '2023-10-10T17:15:00Z'
    LastModifiedDate: '2023-10-10T17:52:00Z'
