- Target: openaf/ojobrt:latest (alpine 3.18.2)
  Class: os-pkgs
  Type: alpine
  Vulnerabilities:
  - VulnerabilityID: CVE-2023-3446
    PkgID: libcrypto3@3.1.1-r2
    PkgName: libcrypto3
    InstalledVersion: 3.1.1-r2
    FixedVersion: 3.1.1-r3
    Layer:
      Digest: sha256:28e1a88b04660107ff3c56ea5eeaf5da23646e4b913cfda654539ce093bb7eb0
      DiffID: sha256:268328d77756c839177fc725c057832321bc67ee6866c22e780225e85fd1f97d
    SeveritySource: nvd
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2023-3446
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: Excessive time spent checking DH keys and parameters
    Description: |-
      Issue summary: Checking excessively long DH keys or parameters may be very slow.

      Impact summary: Applications that use the functions DH_check(), DH_check_ex()
      or EVP_PKEY_param_check() to check a DH key or DH parameters may experience long
      delays. Where the key or parameters that are being checked have been obtained
      from an untrusted source this may lead to a Denial of Service.

      The function DH_check() performs various checks on DH parameters. One of those
      checks confirms that the modulus ('p' parameter) is not too large. Trying to use
      a very large modulus is slow and OpenSSL will not normally use a modulus which
      is over 10,000 bits in length.

      However the DH_check() function checks numerous aspects of the key or parameters
      that have been supplied. Some of those checks use the supplied modulus value
      even if it has already been found to be too large.

      An application that calls DH_check() and supplies a key or parameters obtained
      from an untrusted source could be vulernable to a Denial of Service attack.

      The function DH_check() is itself called by a number of other OpenSSL functions.
      An application calling any of those other functions may similarly be affected.
      The other functions affected by this are DH_check_ex() and
      EVP_PKEY_param_check().

      Also vulnerable are the OpenSSL dhparam and pkeyparam command line applications
      when using the '-check' option.

      The OpenSSL SSL/TLS implementation is not affected by this issue.
      The OpenSSL 3.0 and 3.1 FIPS providers are not affected by this issue.
    Severity: MEDIUM
    CweIDs:
    - CWE-1333
    CVSS:
      nvd:
        V3Vector: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L
        V3Score: 5.3
      redhat:
        V3Vector: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L
        V3Score: 5.3
    References:
    - http://www.openwall.com/lists/oss-security/2023/07/19/4
    - http://www.openwall.com/lists/oss-security/2023/07/19/5
    - http://www.openwall.com/lists/oss-security/2023/07/19/6
    - https://access.redhat.com/security/cve/CVE-2023-3446
    - https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-3446
    - https://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=1fa20cf2f506113c761777127a38bce5068740eb
    - https://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=8780a896543a654e757db1b9396383f9d8095528
    - https://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=9a0a4d3c1e7138915563c0df4fe6a3f9377b839c
    - https://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=fc9867c1e03c22ebf56943be205202e576aabf23
    - https://nvd.nist.gov/vuln/detail/CVE-2023-3446
    - https://www.cve.org/CVERecord?id=CVE-2023-3446
    - https://www.openssl.org/news/secadv/20230719.txt
    PublishedDate: '2023-07-19T12:15:00Z'
    LastModifiedDate: '2023-07-28T19:02:00Z'
  - VulnerabilityID: CVE-2023-3446
    PkgID: libssl3@3.1.1-r2
    PkgName: libssl3
    InstalledVersion: 3.1.1-r2
    FixedVersion: 3.1.1-r3
    Layer:
      Digest: sha256:28e1a88b04660107ff3c56ea5eeaf5da23646e4b913cfda654539ce093bb7eb0
      DiffID: sha256:268328d77756c839177fc725c057832321bc67ee6866c22e780225e85fd1f97d
    SeveritySource: nvd
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2023-3446
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: Excessive time spent checking DH keys and parameters
    Description: |-
      Issue summary: Checking excessively long DH keys or parameters may be very slow.

      Impact summary: Applications that use the functions DH_check(), DH_check_ex()
      or EVP_PKEY_param_check() to check a DH key or DH parameters may experience long
      delays. Where the key or parameters that are being checked have been obtained
      from an untrusted source this may lead to a Denial of Service.

      The function DH_check() performs various checks on DH parameters. One of those
      checks confirms that the modulus ('p' parameter) is not too large. Trying to use
      a very large modulus is slow and OpenSSL will not normally use a modulus which
      is over 10,000 bits in length.

      However the DH_check() function checks numerous aspects of the key or parameters
      that have been supplied. Some of those checks use the supplied modulus value
      even if it has already been found to be too large.

      An application that calls DH_check() and supplies a key or parameters obtained
      from an untrusted source could be vulernable to a Denial of Service attack.

      The function DH_check() is itself called by a number of other OpenSSL functions.
      An application calling any of those other functions may similarly be affected.
      The other functions affected by this are DH_check_ex() and
      EVP_PKEY_param_check().

      Also vulnerable are the OpenSSL dhparam and pkeyparam command line applications
      when using the '-check' option.

      The OpenSSL SSL/TLS implementation is not affected by this issue.
      The OpenSSL 3.0 and 3.1 FIPS providers are not affected by this issue.
    Severity: MEDIUM
    CweIDs:
    - CWE-1333
    CVSS:
      nvd:
        V3Vector: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L
        V3Score: 5.3
      redhat:
        V3Vector: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L
        V3Score: 5.3
    References:
    - http://www.openwall.com/lists/oss-security/2023/07/19/4
    - http://www.openwall.com/lists/oss-security/2023/07/19/5
    - http://www.openwall.com/lists/oss-security/2023/07/19/6
    - https://access.redhat.com/security/cve/CVE-2023-3446
    - https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-3446
    - https://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=1fa20cf2f506113c761777127a38bce5068740eb
    - https://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=8780a896543a654e757db1b9396383f9d8095528
    - https://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=9a0a4d3c1e7138915563c0df4fe6a3f9377b839c
    - https://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=fc9867c1e03c22ebf56943be205202e576aabf23
    - https://nvd.nist.gov/vuln/detail/CVE-2023-3446
    - https://www.cve.org/CVERecord?id=CVE-2023-3446
    - https://www.openssl.org/news/secadv/20230719.txt
    PublishedDate: '2023-07-19T12:15:00Z'
    LastModifiedDate: '2023-07-28T19:02:00Z'
  - VulnerabilityID: CVE-2023-3446
    PkgID: openssl@3.1.1-r2
    PkgName: openssl
    InstalledVersion: 3.1.1-r2
    FixedVersion: 3.1.1-r3
    Layer:
      Digest: sha256:28e1a88b04660107ff3c56ea5eeaf5da23646e4b913cfda654539ce093bb7eb0
      DiffID: sha256:268328d77756c839177fc725c057832321bc67ee6866c22e780225e85fd1f97d
    SeveritySource: nvd
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2023-3446
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: Excessive time spent checking DH keys and parameters
    Description: |-
      Issue summary: Checking excessively long DH keys or parameters may be very slow.

      Impact summary: Applications that use the functions DH_check(), DH_check_ex()
      or EVP_PKEY_param_check() to check a DH key or DH parameters may experience long
      delays. Where the key or parameters that are being checked have been obtained
      from an untrusted source this may lead to a Denial of Service.

      The function DH_check() performs various checks on DH parameters. One of those
      checks confirms that the modulus ('p' parameter) is not too large. Trying to use
      a very large modulus is slow and OpenSSL will not normally use a modulus which
      is over 10,000 bits in length.

      However the DH_check() function checks numerous aspects of the key or parameters
      that have been supplied. Some of those checks use the supplied modulus value
      even if it has already been found to be too large.

      An application that calls DH_check() and supplies a key or parameters obtained
      from an untrusted source could be vulernable to a Denial of Service attack.

      The function DH_check() is itself called by a number of other OpenSSL functions.
      An application calling any of those other functions may similarly be affected.
      The other functions affected by this are DH_check_ex() and
      EVP_PKEY_param_check().

      Also vulnerable are the OpenSSL dhparam and pkeyparam command line applications
      when using the '-check' option.

      The OpenSSL SSL/TLS implementation is not affected by this issue.
      The OpenSSL 3.0 and 3.1 FIPS providers are not affected by this issue.
    Severity: MEDIUM
    CweIDs:
    - CWE-1333
    CVSS:
      nvd:
        V3Vector: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L
        V3Score: 5.3
      redhat:
        V3Vector: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L
        V3Score: 5.3
    References:
    - http://www.openwall.com/lists/oss-security/2023/07/19/4
    - http://www.openwall.com/lists/oss-security/2023/07/19/5
    - http://www.openwall.com/lists/oss-security/2023/07/19/6
    - https://access.redhat.com/security/cve/CVE-2023-3446
    - https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-3446
    - https://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=1fa20cf2f506113c761777127a38bce5068740eb
    - https://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=8780a896543a654e757db1b9396383f9d8095528
    - https://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=9a0a4d3c1e7138915563c0df4fe6a3f9377b839c
    - https://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=fc9867c1e03c22ebf56943be205202e576aabf23
    - https://nvd.nist.gov/vuln/detail/CVE-2023-3446
    - https://www.cve.org/CVERecord?id=CVE-2023-3446
    - https://www.openssl.org/news/secadv/20230719.txt
    PublishedDate: '2023-07-19T12:15:00Z'
    LastModifiedDate: '2023-07-28T19:02:00Z'
