ojob.io/sec/genSecBadge: ''
image: openaf/ojobrt:latest
file: .github/sec-oJobRT-latest.svg
reportFile: .github/sec-oJobRT-latest.yaml
init: {}
msg: Producing a summary of the results...
__key: report
level: info
options: {}
__format: pm
