- Target: openaf/oaf:8-nightly (alpine 3.20.2)
  Class: os-pkgs
  Type: alpine
- Target: Java
  Class: lang-pkgs
  Type: jar
  Vulnerabilities:
  - VulnerabilityID: CVE-2024-25638
    PkgName: dnsjava:dnsjava
    PkgPath: openaf/openaf.jar
    PkgIdentifier:
      PURL: pkg:maven/dnsjava/dnsjava@3.5.3
      UID: fcd3d0c2bf50859
    InstalledVersion: 3.5.3
    FixedVersion: 3.6.0
    Status: fixed
    Layer:
      Digest: sha256:4bb83ce5bb481aac5ba8af213d52e6124add41e2b7e035663de115643ad83dc1
      DiffID: sha256:f0dd153df54fdcbc69f59a23604a75516946ba0410cf410aefa13b6b86f45fd2
    SeveritySource: ghsa
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2024-25638
    DataSource:
      ID: ghsa
      Name: GitHub Security Advisory Maven
      URL: https://github.com/advisories?query=type%3Areviewed+ecosystem%3Amaven
    Title: 'dnsjava: Improper response validation allowing DNSSEC bypass'
    Description: dnsjava is an implementation of DNS in Java. Records in DNS replies are not checked for their relevance to the query, allowing an attacker to respond with RRs from different zones. This vulnerability is fixed in 3.6.0.
    Severity: HIGH
    CweIDs:
    - CWE-345
    - CWE-349
    VendorSeverity:
      ghsa: 3
      redhat: 3
    CVSS:
      ghsa:
        V3Vector: CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:C/C:H/I:H/A:L
        V3Score: 8.9
      redhat:
        V3Vector: CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:C/C:H/I:H/A:L
        V3Score: 8.9
    References:
    - https://access.redhat.com/security/cve/CVE-2024-25638
    - https://github.com/dnsjava/dnsjava
    - https://github.com/dnsjava/dnsjava/commit/bc51df1c455e6c9fb7cbd42fcb6d62d16047818d
    - https://github.com/dnsjava/dnsjava/security/advisories/GHSA-cfxw-4h78-h7fw
    - https://nvd.nist.gov/vuln/detail/CVE-2024-25638
    - https://www.cve.org/CVERecord?id=CVE-2024-25638
    PublishedDate: '2024-07-22T14:15:04.593Z'
    LastModifiedDate: '2024-07-24T12:55:13.223Z'
  - VulnerabilityID: GHSA-crjg-w57m-rqqf
    PkgName: dnsjava:dnsjava
    PkgPath: openaf/openaf.jar
    PkgIdentifier:
      PURL: pkg:maven/dnsjava/dnsjava@3.5.3
      UID: fcd3d0c2bf50859
    InstalledVersion: 3.5.3
    FixedVersion: 3.6.0
    Status: fixed
    Layer:
      Digest: sha256:4bb83ce5bb481aac5ba8af213d52e6124add41e2b7e035663de115643ad83dc1
      DiffID: sha256:f0dd153df54fdcbc69f59a23604a75516946ba0410cf410aefa13b6b86f45fd2
    SeveritySource: ghsa
    PrimaryURL: https://github.com/advisories/GHSA-crjg-w57m-rqqf
    DataSource:
      ID: ghsa
      Name: GitHub Security Advisory Maven
      URL: https://github.com/advisories?query=type%3Areviewed+ecosystem%3Amaven
    Title: DNSJava vulnerable to KeyTrap - Denial-of-Service Algorithmic Complexity Attacks
    Description: |
      ### Impact
      Users using the `ValidatingResolver` for DNSSEC validation can run into CPU exhaustion with specially crafted DNSSEC-signed zones.

      ### Patches
      Users should upgrade to dnsjava v3.6.0

      ### Workarounds
      Although not recommended, only using a non-validating resolver, will remove the vulnerability. 

      ### References
      https://www.athene-center.de/en/keytrap
    Severity: MEDIUM
    VendorSeverity:
      ghsa: 2
    CVSS:
      ghsa:
        V3Vector: CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H
        V3Score: 6.5
    References:
    - https://github.com/dnsjava/dnsjava
    - https://github.com/dnsjava/dnsjava/commit/07ac36a11578cc1bce0cd8ddf2fe568f062aee78
    - https://github.com/dnsjava/dnsjava/commit/3ddc45ce8cdb5c2274e10b7401416f497694e1cf
    - https://github.com/dnsjava/dnsjava/security/advisories/GHSA-crjg-w57m-rqqf
  - VulnerabilityID: GHSA-mmwx-rj87-vfgr
    PkgName: dnsjava:dnsjava
    PkgPath: openaf/openaf.jar
    PkgIdentifier:
      PURL: pkg:maven/dnsjava/dnsjava@3.5.3
      UID: fcd3d0c2bf50859
    InstalledVersion: 3.5.3
    FixedVersion: 3.6.0
    Status: fixed
    Layer:
      Digest: sha256:4bb83ce5bb481aac5ba8af213d52e6124add41e2b7e035663de115643ad83dc1
      DiffID: sha256:f0dd153df54fdcbc69f59a23604a75516946ba0410cf410aefa13b6b86f45fd2
    SeveritySource: ghsa
    PrimaryURL: https://github.com/advisories/GHSA-mmwx-rj87-vfgr
    DataSource:
      ID: ghsa
      Name: GitHub Security Advisory Maven
      URL: https://github.com/advisories?query=type%3Areviewed+ecosystem%3Amaven
    Title: DNSJava affected by KeyTrap - NSEC3 closest encloser proof can exhaust CPU resources
    Description: |
      ### Impact
      Users using the `ValidatingResolver` for DNSSEC validation can run into CPU exhaustion with specially crafted DNSSEC-signed zones.

      ### Patches
      Users should upgrade to dnsjava v3.6.0

      ### Workarounds
      Although not recommended, only using a non-validating resolver, will remove the vulnerability.

      ### References
      https://www.athene-center.de/en/keytrap
    Severity: MEDIUM
    VendorSeverity:
      ghsa: 2
    CVSS:
      ghsa:
        V3Vector: CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H
        V3Score: 6.5
    References:
    - https://github.com/dnsjava/dnsjava
    - https://github.com/dnsjava/dnsjava/commit/711af79be3214f52daa5c846b95766dc0a075116
    - https://github.com/dnsjava/dnsjava/security/advisories/GHSA-mmwx-rj87-vfgr
