- Target: openaf/oaf:8-nightly (alpine 3.19.1)
  Class: os-pkgs
  Type: alpine
  Vulnerabilities:
  - VulnerabilityID: CVE-2023-42363
    PkgID: busybox@1.36.1-r15
    PkgName: busybox
    PkgIdentifier:
      PURL: pkg:apk/alpine/busybox@1.36.1-r15?arch=x86_64&distro=3.19.1
      UID: a71bca140ff5726b
    InstalledVersion: 1.36.1-r15
    FixedVersion: 1.36.1-r17
    Status: fixed
    Layer:
      Digest: sha256:eaf3927df1b97ee058afb0654692364b184717bdc3a0dec556ba93881b5ee9fa
      DiffID: sha256:6b12f7b60b32f786c21a41e0c2244588d46d92bc394c55167a268c43e04f4e0e
    SeveritySource: nvd
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2023-42363
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'busybox: use-after-free in awk'
    Description: A use-after-free vulnerability was discovered in xasprintf function in xfuncs_printf.c:344 in BusyBox v.1.36.1.
    Severity: MEDIUM
    CweIDs:
    - CWE-416
    VendorSeverity:
      nvd: 2
      redhat: 2
      ubuntu: 2
    CVSS:
      nvd:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H
        V3Score: 5.5
      redhat:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H
        V3Score: 7.8
    References:
    - https://access.redhat.com/security/cve/CVE-2023-42363
    - https://bugs.busybox.net/show_bug.cgi?id=15865
    - https://nvd.nist.gov/vuln/detail/CVE-2023-42363
    - https://www.cve.org/CVERecord?id=CVE-2023-42363
    PublishedDate: '2023-11-27T22:15:07.94Z'
    LastModifiedDate: '2023-11-30T05:06:49.523Z'
  - VulnerabilityID: CVE-2023-42364
    PkgID: busybox@1.36.1-r15
    PkgName: busybox
    PkgIdentifier:
      PURL: pkg:apk/alpine/busybox@1.36.1-r15?arch=x86_64&distro=3.19.1
      UID: a71bca140ff5726b
    InstalledVersion: 1.36.1-r15
    FixedVersion: 1.36.1-r17
    Status: fixed
    Layer:
      Digest: sha256:eaf3927df1b97ee058afb0654692364b184717bdc3a0dec556ba93881b5ee9fa
      DiffID: sha256:6b12f7b60b32f786c21a41e0c2244588d46d92bc394c55167a268c43e04f4e0e
    SeveritySource: nvd
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2023-42364
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'busybox: use-after-free'
    Description: A use-after-free vulnerability in BusyBox v.1.36.1 allows attackers to cause a denial of service via a crafted awk pattern in the awk.c evaluate function.
    Severity: MEDIUM
    CweIDs:
    - CWE-416
    VendorSeverity:
      nvd: 2
      redhat: 2
      ubuntu: 2
    CVSS:
      nvd:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H
        V3Score: 5.5
      redhat:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H
        V3Score: 7.8
    References:
    - https://access.redhat.com/security/cve/CVE-2023-42364
    - https://bugs.busybox.net/show_bug.cgi?id=15868
    - https://nvd.nist.gov/vuln/detail/CVE-2023-42364
    - https://www.cve.org/CVERecord?id=CVE-2023-42364
    PublishedDate: '2023-11-27T23:15:07.313Z'
    LastModifiedDate: '2023-11-30T05:07:10.827Z'
  - VulnerabilityID: CVE-2023-42365
    PkgID: busybox@1.36.1-r15
    PkgName: busybox
    PkgIdentifier:
      PURL: pkg:apk/alpine/busybox@1.36.1-r15?arch=x86_64&distro=3.19.1
      UID: a71bca140ff5726b
    InstalledVersion: 1.36.1-r15
    FixedVersion: 1.36.1-r17
    Status: fixed
    Layer:
      Digest: sha256:eaf3927df1b97ee058afb0654692364b184717bdc3a0dec556ba93881b5ee9fa
      DiffID: sha256:6b12f7b60b32f786c21a41e0c2244588d46d92bc394c55167a268c43e04f4e0e
    SeveritySource: nvd
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2023-42365
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'busybox:  use-after-free'
    Description: A use-after-free vulnerability was discovered in BusyBox v.1.36.1 via a crafted awk pattern in the awk.c copyvar function.
    Severity: MEDIUM
    CweIDs:
    - CWE-416
    VendorSeverity:
      nvd: 2
      redhat: 2
      ubuntu: 2
    CVSS:
      nvd:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H
        V3Score: 5.5
      redhat:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H
        V3Score: 7.8
    References:
    - https://access.redhat.com/security/cve/CVE-2023-42365
    - https://bugs.busybox.net/show_bug.cgi?id=15871
    - https://nvd.nist.gov/vuln/detail/CVE-2023-42365
    - https://www.cve.org/CVERecord?id=CVE-2023-42365
    PublishedDate: '2023-11-27T23:15:07.373Z'
    LastModifiedDate: '2023-11-30T05:08:08.77Z'
  - VulnerabilityID: CVE-2023-42366
    PkgID: busybox@1.36.1-r15
    PkgName: busybox
    PkgIdentifier:
      PURL: pkg:apk/alpine/busybox@1.36.1-r15?arch=x86_64&distro=3.19.1
      UID: a71bca140ff5726b
    InstalledVersion: 1.36.1-r15
    FixedVersion: 1.36.1-r16
    Status: fixed
    Layer:
      Digest: sha256:eaf3927df1b97ee058afb0654692364b184717bdc3a0dec556ba93881b5ee9fa
      DiffID: sha256:6b12f7b60b32f786c21a41e0c2244588d46d92bc394c55167a268c43e04f4e0e
    SeveritySource: nvd
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2023-42366
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'busybox: A heap-buffer-overflow'
    Description: A heap-buffer-overflow was discovered in BusyBox v.1.36.1 in the next_token function at awk.c:1159.
    Severity: MEDIUM
    CweIDs:
    - CWE-787
    VendorSeverity:
      nvd: 2
      redhat: 2
      ubuntu: 2
    CVSS:
      nvd:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H
        V3Score: 5.5
      redhat:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:N/A:H
        V3Score: 7.1
    References:
    - https://access.redhat.com/security/cve/CVE-2023-42366
    - https://bugs.busybox.net/show_bug.cgi?id=15874
    - https://nvd.nist.gov/vuln/detail/CVE-2023-42366
    - https://www.cve.org/CVERecord?id=CVE-2023-42366
    PublishedDate: '2023-11-27T23:15:07.42Z'
    LastModifiedDate: '2023-11-30T05:08:23.197Z'
  - VulnerabilityID: CVE-2023-42363
    PkgID: busybox-binsh@1.36.1-r15
    PkgName: busybox-binsh
    PkgIdentifier:
      PURL: pkg:apk/alpine/busybox-binsh@1.36.1-r15?arch=x86_64&distro=3.19.1
      UID: 3c2acc699fbc7b01
    InstalledVersion: 1.36.1-r15
    FixedVersion: 1.36.1-r17
    Status: fixed
    Layer:
      Digest: sha256:eaf3927df1b97ee058afb0654692364b184717bdc3a0dec556ba93881b5ee9fa
      DiffID: sha256:6b12f7b60b32f786c21a41e0c2244588d46d92bc394c55167a268c43e04f4e0e
    SeveritySource: nvd
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2023-42363
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'busybox: use-after-free in awk'
    Description: A use-after-free vulnerability was discovered in xasprintf function in xfuncs_printf.c:344 in BusyBox v.1.36.1.
    Severity: MEDIUM
    CweIDs:
    - CWE-416
    VendorSeverity:
      nvd: 2
      redhat: 2
      ubuntu: 2
    CVSS:
      nvd:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H
        V3Score: 5.5
      redhat:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H
        V3Score: 7.8
    References:
    - https://access.redhat.com/security/cve/CVE-2023-42363
    - https://bugs.busybox.net/show_bug.cgi?id=15865
    - https://nvd.nist.gov/vuln/detail/CVE-2023-42363
    - https://www.cve.org/CVERecord?id=CVE-2023-42363
    PublishedDate: '2023-11-27T22:15:07.94Z'
    LastModifiedDate: '2023-11-30T05:06:49.523Z'
  - VulnerabilityID: CVE-2023-42364
    PkgID: busybox-binsh@1.36.1-r15
    PkgName: busybox-binsh
    PkgIdentifier:
      PURL: pkg:apk/alpine/busybox-binsh@1.36.1-r15?arch=x86_64&distro=3.19.1
      UID: 3c2acc699fbc7b01
    InstalledVersion: 1.36.1-r15
    FixedVersion: 1.36.1-r17
    Status: fixed
    Layer:
      Digest: sha256:eaf3927df1b97ee058afb0654692364b184717bdc3a0dec556ba93881b5ee9fa
      DiffID: sha256:6b12f7b60b32f786c21a41e0c2244588d46d92bc394c55167a268c43e04f4e0e
    SeveritySource: nvd
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2023-42364
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'busybox: use-after-free'
    Description: A use-after-free vulnerability in BusyBox v.1.36.1 allows attackers to cause a denial of service via a crafted awk pattern in the awk.c evaluate function.
    Severity: MEDIUM
    CweIDs:
    - CWE-416
    VendorSeverity:
      nvd: 2
      redhat: 2
      ubuntu: 2
    CVSS:
      nvd:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H
        V3Score: 5.5
      redhat:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H
        V3Score: 7.8
    References:
    - https://access.redhat.com/security/cve/CVE-2023-42364
    - https://bugs.busybox.net/show_bug.cgi?id=15868
    - https://nvd.nist.gov/vuln/detail/CVE-2023-42364
    - https://www.cve.org/CVERecord?id=CVE-2023-42364
    PublishedDate: '2023-11-27T23:15:07.313Z'
    LastModifiedDate: '2023-11-30T05:07:10.827Z'
  - VulnerabilityID: CVE-2023-42365
    PkgID: busybox-binsh@1.36.1-r15
    PkgName: busybox-binsh
    PkgIdentifier:
      PURL: pkg:apk/alpine/busybox-binsh@1.36.1-r15?arch=x86_64&distro=3.19.1
      UID: 3c2acc699fbc7b01
    InstalledVersion: 1.36.1-r15
    FixedVersion: 1.36.1-r17
    Status: fixed
    Layer:
      Digest: sha256:eaf3927df1b97ee058afb0654692364b184717bdc3a0dec556ba93881b5ee9fa
      DiffID: sha256:6b12f7b60b32f786c21a41e0c2244588d46d92bc394c55167a268c43e04f4e0e
    SeveritySource: nvd
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2023-42365
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'busybox:  use-after-free'
    Description: A use-after-free vulnerability was discovered in BusyBox v.1.36.1 via a crafted awk pattern in the awk.c copyvar function.
    Severity: MEDIUM
    CweIDs:
    - CWE-416
    VendorSeverity:
      nvd: 2
      redhat: 2
      ubuntu: 2
    CVSS:
      nvd:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H
        V3Score: 5.5
      redhat:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H
        V3Score: 7.8
    References:
    - https://access.redhat.com/security/cve/CVE-2023-42365
    - https://bugs.busybox.net/show_bug.cgi?id=15871
    - https://nvd.nist.gov/vuln/detail/CVE-2023-42365
    - https://www.cve.org/CVERecord?id=CVE-2023-42365
    PublishedDate: '2023-11-27T23:15:07.373Z'
    LastModifiedDate: '2023-11-30T05:08:08.77Z'
  - VulnerabilityID: CVE-2023-42366
    PkgID: busybox-binsh@1.36.1-r15
    PkgName: busybox-binsh
    PkgIdentifier:
      PURL: pkg:apk/alpine/busybox-binsh@1.36.1-r15?arch=x86_64&distro=3.19.1
      UID: 3c2acc699fbc7b01
    InstalledVersion: 1.36.1-r15
    FixedVersion: 1.36.1-r16
    Status: fixed
    Layer:
      Digest: sha256:eaf3927df1b97ee058afb0654692364b184717bdc3a0dec556ba93881b5ee9fa
      DiffID: sha256:6b12f7b60b32f786c21a41e0c2244588d46d92bc394c55167a268c43e04f4e0e
    SeveritySource: nvd
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2023-42366
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'busybox: A heap-buffer-overflow'
    Description: A heap-buffer-overflow was discovered in BusyBox v.1.36.1 in the next_token function at awk.c:1159.
    Severity: MEDIUM
    CweIDs:
    - CWE-787
    VendorSeverity:
      nvd: 2
      redhat: 2
      ubuntu: 2
    CVSS:
      nvd:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H
        V3Score: 5.5
      redhat:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:N/A:H
        V3Score: 7.1
    References:
    - https://access.redhat.com/security/cve/CVE-2023-42366
    - https://bugs.busybox.net/show_bug.cgi?id=15874
    - https://nvd.nist.gov/vuln/detail/CVE-2023-42366
    - https://www.cve.org/CVERecord?id=CVE-2023-42366
    PublishedDate: '2023-11-27T23:15:07.42Z'
    LastModifiedDate: '2023-11-30T05:08:23.197Z'
  - VulnerabilityID: CVE-2023-42363
    PkgID: ssl_client@1.36.1-r15
    PkgName: ssl_client
    PkgIdentifier:
      PURL: pkg:apk/alpine/ssl_client@1.36.1-r15?arch=x86_64&distro=3.19.1
      UID: 741efa5e56ecac21
    InstalledVersion: 1.36.1-r15
    FixedVersion: 1.36.1-r17
    Status: fixed
    Layer:
      Digest: sha256:eaf3927df1b97ee058afb0654692364b184717bdc3a0dec556ba93881b5ee9fa
      DiffID: sha256:6b12f7b60b32f786c21a41e0c2244588d46d92bc394c55167a268c43e04f4e0e
    SeveritySource: nvd
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2023-42363
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'busybox: use-after-free in awk'
    Description: A use-after-free vulnerability was discovered in xasprintf function in xfuncs_printf.c:344 in BusyBox v.1.36.1.
    Severity: MEDIUM
    CweIDs:
    - CWE-416
    VendorSeverity:
      nvd: 2
      redhat: 2
      ubuntu: 2
    CVSS:
      nvd:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H
        V3Score: 5.5
      redhat:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H
        V3Score: 7.8
    References:
    - https://access.redhat.com/security/cve/CVE-2023-42363
    - https://bugs.busybox.net/show_bug.cgi?id=15865
    - https://nvd.nist.gov/vuln/detail/CVE-2023-42363
    - https://www.cve.org/CVERecord?id=CVE-2023-42363
    PublishedDate: '2023-11-27T22:15:07.94Z'
    LastModifiedDate: '2023-11-30T05:06:49.523Z'
  - VulnerabilityID: CVE-2023-42364
    PkgID: ssl_client@1.36.1-r15
    PkgName: ssl_client
    PkgIdentifier:
      PURL: pkg:apk/alpine/ssl_client@1.36.1-r15?arch=x86_64&distro=3.19.1
      UID: 741efa5e56ecac21
    InstalledVersion: 1.36.1-r15
    FixedVersion: 1.36.1-r17
    Status: fixed
    Layer:
      Digest: sha256:eaf3927df1b97ee058afb0654692364b184717bdc3a0dec556ba93881b5ee9fa
      DiffID: sha256:6b12f7b60b32f786c21a41e0c2244588d46d92bc394c55167a268c43e04f4e0e
    SeveritySource: nvd
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2023-42364
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'busybox: use-after-free'
    Description: A use-after-free vulnerability in BusyBox v.1.36.1 allows attackers to cause a denial of service via a crafted awk pattern in the awk.c evaluate function.
    Severity: MEDIUM
    CweIDs:
    - CWE-416
    VendorSeverity:
      nvd: 2
      redhat: 2
      ubuntu: 2
    CVSS:
      nvd:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H
        V3Score: 5.5
      redhat:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H
        V3Score: 7.8
    References:
    - https://access.redhat.com/security/cve/CVE-2023-42364
    - https://bugs.busybox.net/show_bug.cgi?id=15868
    - https://nvd.nist.gov/vuln/detail/CVE-2023-42364
    - https://www.cve.org/CVERecord?id=CVE-2023-42364
    PublishedDate: '2023-11-27T23:15:07.313Z'
    LastModifiedDate: '2023-11-30T05:07:10.827Z'
  - VulnerabilityID: CVE-2023-42365
    PkgID: ssl_client@1.36.1-r15
    PkgName: ssl_client
    PkgIdentifier:
      PURL: pkg:apk/alpine/ssl_client@1.36.1-r15?arch=x86_64&distro=3.19.1
      UID: 741efa5e56ecac21
    InstalledVersion: 1.36.1-r15
    FixedVersion: 1.36.1-r17
    Status: fixed
    Layer:
      Digest: sha256:eaf3927df1b97ee058afb0654692364b184717bdc3a0dec556ba93881b5ee9fa
      DiffID: sha256:6b12f7b60b32f786c21a41e0c2244588d46d92bc394c55167a268c43e04f4e0e
    SeveritySource: nvd
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2023-42365
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'busybox:  use-after-free'
    Description: A use-after-free vulnerability was discovered in BusyBox v.1.36.1 via a crafted awk pattern in the awk.c copyvar function.
    Severity: MEDIUM
    CweIDs:
    - CWE-416
    VendorSeverity:
      nvd: 2
      redhat: 2
      ubuntu: 2
    CVSS:
      nvd:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H
        V3Score: 5.5
      redhat:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H
        V3Score: 7.8
    References:
    - https://access.redhat.com/security/cve/CVE-2023-42365
    - https://bugs.busybox.net/show_bug.cgi?id=15871
    - https://nvd.nist.gov/vuln/detail/CVE-2023-42365
    - https://www.cve.org/CVERecord?id=CVE-2023-42365
    PublishedDate: '2023-11-27T23:15:07.373Z'
    LastModifiedDate: '2023-11-30T05:08:08.77Z'
  - VulnerabilityID: CVE-2023-42366
    PkgID: ssl_client@1.36.1-r15
    PkgName: ssl_client
    PkgIdentifier:
      PURL: pkg:apk/alpine/ssl_client@1.36.1-r15?arch=x86_64&distro=3.19.1
      UID: 741efa5e56ecac21
    InstalledVersion: 1.36.1-r15
    FixedVersion: 1.36.1-r16
    Status: fixed
    Layer:
      Digest: sha256:eaf3927df1b97ee058afb0654692364b184717bdc3a0dec556ba93881b5ee9fa
      DiffID: sha256:6b12f7b60b32f786c21a41e0c2244588d46d92bc394c55167a268c43e04f4e0e
    SeveritySource: nvd
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2023-42366
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'busybox: A heap-buffer-overflow'
    Description: A heap-buffer-overflow was discovered in BusyBox v.1.36.1 in the next_token function at awk.c:1159.
    Severity: MEDIUM
    CweIDs:
    - CWE-787
    VendorSeverity:
      nvd: 2
      redhat: 2
      ubuntu: 2
    CVSS:
      nvd:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H
        V3Score: 5.5
      redhat:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:N/A:H
        V3Score: 7.1
    References:
    - https://access.redhat.com/security/cve/CVE-2023-42366
    - https://bugs.busybox.net/show_bug.cgi?id=15874
    - https://nvd.nist.gov/vuln/detail/CVE-2023-42366
    - https://www.cve.org/CVERecord?id=CVE-2023-42366
    PublishedDate: '2023-11-27T23:15:07.42Z'
    LastModifiedDate: '2023-11-30T05:08:23.197Z'
