- Target: openaf/ojobrt:edge (alpine 3.22.0_alpha20250108)
  Class: os-pkgs
  Type: alpine
  Vulnerabilities:
  - VulnerabilityID: CVE-2025-26519
    PkgID: musl@1.2.5-r9
    PkgName: musl
    PkgIdentifier:
      PURL: pkg:apk/alpine/musl@1.2.5-r9?arch=x86_64&distro=3.22.0_alpha20250108
      UID: ebcbb7de0538c04f
    InstalledVersion: 1.2.5-r9
    FixedVersion: 1.2.5-r10
    Status: fixed
    Layer:
      Digest: sha256:a72f5ca273b0eced52affb6eba7ee063777801cd80ca1efe77517a6060124438
      DiffID: sha256:e99488328a725bdebcd0b28259de742b2d890a88efb59874aca5ffbad905d295
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2025-26519
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: musl libc 0.9.13 through 1.2.5 before 1.2.6 has an out-of-bounds write ...
    Description: musl libc 0.9.13 through 1.2.5 before 1.2.6 has an out-of-bounds write vulnerability when an attacker can trigger iconv conversion of untrusted EUC-KR text to UTF-8.
    Severity: UNKNOWN
    CweIDs:
    - CWE-787
    References:
    - http://www.openwall.com/lists/oss-security/2025/02/13/2
    - http://www.openwall.com/lists/oss-security/2025/02/13/3
    - http://www.openwall.com/lists/oss-security/2025/02/13/4
    - http://www.openwall.com/lists/oss-security/2025/02/13/5
    - http://www.openwall.com/lists/oss-security/2025/02/14/5
    - http://www.openwall.com/lists/oss-security/2025/02/14/6
    - https://git.musl-libc.org/cgit/musl/commit/?id=c47ad25ea3b484e10326f933e927c0bc8cded3da
    - https://git.musl-libc.org/cgit/musl/commit/?id=e5adcd97b5196e29991b524237381a0202a60659
    - https://www.openwall.com/lists/oss-security/2025/02/13/2
    PublishedDate: '2025-02-14T04:15:09.05Z'
    LastModifiedDate: '2025-02-14T17:15:23.09Z'
  - VulnerabilityID: CVE-2025-26519
    PkgID: musl-utils@1.2.5-r9
    PkgName: musl-utils
    PkgIdentifier:
      PURL: pkg:apk/alpine/musl-utils@1.2.5-r9?arch=x86_64&distro=3.22.0_alpha20250108
      UID: 8b959e5d6017bacb
    InstalledVersion: 1.2.5-r9
    FixedVersion: 1.2.5-r10
    Status: fixed
    Layer:
      Digest: sha256:a72f5ca273b0eced52affb6eba7ee063777801cd80ca1efe77517a6060124438
      DiffID: sha256:e99488328a725bdebcd0b28259de742b2d890a88efb59874aca5ffbad905d295
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2025-26519
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: musl libc 0.9.13 through 1.2.5 before 1.2.6 has an out-of-bounds write ...
    Description: musl libc 0.9.13 through 1.2.5 before 1.2.6 has an out-of-bounds write vulnerability when an attacker can trigger iconv conversion of untrusted EUC-KR text to UTF-8.
    Severity: UNKNOWN
    CweIDs:
    - CWE-787
    References:
    - http://www.openwall.com/lists/oss-security/2025/02/13/2
    - http://www.openwall.com/lists/oss-security/2025/02/13/3
    - http://www.openwall.com/lists/oss-security/2025/02/13/4
    - http://www.openwall.com/lists/oss-security/2025/02/13/5
    - http://www.openwall.com/lists/oss-security/2025/02/14/5
    - http://www.openwall.com/lists/oss-security/2025/02/14/6
    - https://git.musl-libc.org/cgit/musl/commit/?id=c47ad25ea3b484e10326f933e927c0bc8cded3da
    - https://git.musl-libc.org/cgit/musl/commit/?id=e5adcd97b5196e29991b524237381a0202a60659
    - https://www.openwall.com/lists/oss-security/2025/02/13/2
    PublishedDate: '2025-02-14T04:15:09.05Z'
    LastModifiedDate: '2025-02-14T17:15:23.09Z'
- Target: Java
  Class: lang-pkgs
  Type: jar
  Vulnerabilities:
  - VulnerabilityID: GHSA-h7rh-xfpj-hpcm
    PkgName: io.minio:minio
    PkgPath: openaf/S3/minio-8.5.17.jar
    PkgIdentifier:
      PURL: pkg:maven/io.minio/minio@8.5.17
      UID: f8170235ced54720
    InstalledVersion: 8.5.17
    FixedVersion: 8.6.0
    Status: fixed
    Layer:
      Digest: sha256:4bac41638c41d827edab35791307a8bf05b1fd1c36ef13f91f0c5d910e693f4c
      DiffID: sha256:87a90cf62df9bb93a48653301205239be571a6d24ec0f976cec7e67ef6e220bb
    SeveritySource: ghsa
    PrimaryURL: https://github.com/advisories/GHSA-h7rh-xfpj-hpcm
    DataSource:
      ID: ghsa
      Name: GitHub Security Advisory Maven
      URL: https://github.com/advisories?query=type%3Areviewed+ecosystem%3Amaven
    Title: MinIO Java Client XML Tag Value Substitution Vulnerability
    Description: |-
      #### Description
      In minio-java versions prior to 8.6.0, XML tag values containing references to system properties or environment variables were automatically substituted with their actual values during processing. This unintended behavior could lead to the exposure of sensitive information, including credentials, file paths, or system configuration details, if such references were present in XML content from untrusted sources.

      #### Affected Versions
      - minio-java < 8.6.0

      All applications utilizing affected versions of minio-java for parsing XML with potentially untrusted input are vulnerable.

      #### Impact
      This vulnerability poses a high risk of information disclosure. Attackers could craft malicious XML inputs to extract sensitive data from the system's properties or environment variables, potentially compromising security in applications relying on minio-java for object storage operations.

      #### Patches
      The issue is resolved in minio-java version 8.6.0 and later. In these versions, automatic substitution of XML tag values with system properties or environment variables has been disabled.

      Users are strongly advised to upgrade to minio-java 8.6.0 or a newer release to mitigate the vulnerability.

      #### Workarounds
      No full workarounds exist without upgrading the library. As interim measures:

      - Refrain from processing XML data from untrusted or external sources.
      - Implement input sanitization or validation to detect and remove references to 
        system properties or environment variables in XML content.
    Severity: HIGH
    VendorSeverity:
      ghsa: 3
    References:
    - https://github.com/minio/minio-java
    - https://github.com/minio/minio-java/commit/f7a98d06b25e5464bdd4811b044e25ff9101d37f
    - https://github.com/minio/minio-java/releases/tag/8.6.0
    - https://github.com/minio/minio-java/security/advisories/GHSA-h7rh-xfpj-hpcm
    PublishedDate: '2025-09-29T17:53:31Z'
    LastModifiedDate: '2025-09-29T17:53:31Z'
