ojob.io/sec/genSecBadge: ''
image: openaf/ojobrt:8-nightly
file: .github/sec-8-oJobRT-nightly.svg
reportFile: .github/sec-8-oJobRT-nightly.yaml
init: {}
msg: Producing a summary of the results...
__key: report
level: info
options: {}
__format: pm
