- Target: openaf/ojobrt:nightly (alpine 3.21.2)
  Class: os-pkgs
  Type: alpine
  Vulnerabilities:
  - VulnerabilityID: CVE-2025-26519
    PkgID: musl@1.2.5-r8
    PkgName: musl
    PkgIdentifier:
      PURL: pkg:apk/alpine/musl@1.2.5-r8?arch=x86_64&distro=3.21.2
      UID: 936f1fd92822db90
    InstalledVersion: 1.2.5-r8
    FixedVersion: 1.2.5-r9
    Status: fixed
    Layer:
      Digest: sha256:39a262114ead8f09f6e0df621a162dd459f982b165c889f9bc890ca9bedf0b44
      DiffID: sha256:21a847210d4069ff0170c5d7efa2bc7b88b8ef3b740d6508313cd32e501ae444
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Severity: UNKNOWN
  - VulnerabilityID: CVE-2025-26519
    PkgID: musl-utils@1.2.5-r8
    PkgName: musl-utils
    PkgIdentifier:
      PURL: pkg:apk/alpine/musl-utils@1.2.5-r8?arch=x86_64&distro=3.21.2
      UID: f25fd050ed07b9ad
    InstalledVersion: 1.2.5-r8
    FixedVersion: 1.2.5-r9
    Status: fixed
    Layer:
      Digest: sha256:39a262114ead8f09f6e0df621a162dd459f982b165c889f9bc890ca9bedf0b44
      DiffID: sha256:21a847210d4069ff0170c5d7efa2bc7b88b8ef3b740d6508313cd32e501ae444
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Severity: UNKNOWN
- Target: Java
  Class: lang-pkgs
  Type: jar
