ojob.io/sec/genSecBadge: ''
image: openaf/oaf:8-ubi-nightly
file: .github/sec-8-ubi-nightly.svg
reportFile: .github/sec-8-ubi-nightly.yaml
init: {}
msg: Producing a summary of the results...
__key: report
level: info
options: {}
__format: pm
