- Target: openaf/oaf:edge (alpine 3.24.2)
  Class: os-pkgs
  Type: alpine
  Packages: []
  Vulnerabilities:
  - VulnerabilityID: CVE-2026-85091
    PkgID: zlib@1.3.2-r0
    PkgName: zlib
    PkgIdentifier:
      PURL: pkg:apk/alpine/zlib@1.3.2-r0?arch=x86_64&distro=3.24.2
      UID: e37054a2982d6c16
    InstalledVersion: 1.3.2-r0
    FixedVersion: 1.3.2-r1
    Status: fixed
    Layer:
      Digest: sha256:df8a23416522ee8f27e15775ec6219f444cdbde7171181e7f6e94eec12004f0d
      DiffID: sha256:286b9348280360949433489374be9ad7886a20888c55f7273420cbe566031eef
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2026-85091
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Fingerprint: sha256:55676b08bf3e6e2ee82f50f042d1ce20d1287315e7ef406c4b24310a3eca197e
    Title: zlib versions 1.3.1.2 through 1.3.2 contain a heap buffer overflow vul ...
    Description: zlib versions 1.3.1.2 through 1.3.2 contain a heap buffer overflow vulnerability in the gz_vacate() function when processing non-blocking gzwrite() operations with stale external buffer pointers. Attackers can trigger the overflow by calling gzprintf() or gzvprintf() after a write stall, causing an unchecked memmove() to write beyond the internal input buffer boundary.
    Severity: MEDIUM
    CweIDs:
    - CWE-787
    VendorSeverity:
      ubuntu: 2
    References:
    - https://gist.github.com/thesmartshadow/e0b9481792afb7c31e86fee1ff084490
    - https://github.com/madler/zlib
    - https://github.com/madler/zlib/blob/v1.3.2/gzwrite.c#L393
    - https://www.cve.org/CVERecord?id=CVE-2026-85091
    - https://www.vulncheck.com/advisories/zlib-1.3.1.2-through-1.3.2-heap-buffer-overflow-via-gz-vacate
    PublishedDate: '2026-09-03T13:06:20.573Z'
    LastModifiedDate: '2026-09-09T20:41:07.123Z'
- Target: Java
  Class: lang-pkgs
  Type: jar
  Packages: []
