- Target: openaf/ojobrt:nightly (alpine 3.21.2)
  Class: os-pkgs
  Type: alpine
  Vulnerabilities:
  - VulnerabilityID: CVE-2025-0725
    PkgID: curl@8.11.1-r1
    PkgName: curl
    PkgIdentifier:
      PURL: pkg:apk/alpine/curl@8.11.1-r1?arch=x86_64&distro=3.21.2
      UID: 6c52f830beb86792
    InstalledVersion: 8.11.1-r1
    FixedVersion: 8.12.0-r0
    Status: fixed
    Layer:
      Digest: sha256:5a7a8fdc52f48911c3b59dfa3ea757ad5386ecc585c664f35ddce1d17bc1966f
      DiffID: sha256:b56fb45dbc09c27803605502b2c6d859670ce70d16087217d901e1755f68f118
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2025-0725
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'libcurl: Buffer Overflow in libcurl via zlib Integer Overflow'
    Description: |-
      When libcurl is asked to perform automatic gzip decompression of
      content-encoded HTTP responses with the `CURLOPT_ACCEPT_ENCODING` option,
      **using zlib 1.2.0.3 or older**, an attacker-controlled integer overflow would
      make libcurl perform a buffer overflow.
    Severity: MEDIUM
    VendorSeverity:
      redhat: 1
    CVSS:
      redhat:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L
        V3Score: 4
    References:
    - http://www.openwall.com/lists/oss-security/2025/02/05/3
    - http://www.openwall.com/lists/oss-security/2025/02/06/2
    - http://www.openwall.com/lists/oss-security/2025/02/06/4
    - https://access.redhat.com/security/cve/CVE-2025-0725
    - https://curl.se/docs/CVE-2025-0725.html
    - https://curl.se/docs/CVE-2025-0725.json
    - https://hackerone.com/reports/2956023
    - https://nvd.nist.gov/vuln/detail/CVE-2025-0725
    - https://www.cve.org/CVERecord?id=CVE-2025-0725
    PublishedDate: '2025-02-05T10:15:22.98Z'
    LastModifiedDate: '2025-02-06T19:15:19.733Z'
  - VulnerabilityID: CVE-2025-0167
    PkgID: curl@8.11.1-r1
    PkgName: curl
    PkgIdentifier:
      PURL: pkg:apk/alpine/curl@8.11.1-r1?arch=x86_64&distro=3.21.2
      UID: 6c52f830beb86792
    InstalledVersion: 8.11.1-r1
    FixedVersion: 8.12.0-r0
    Status: fixed
    Layer:
      Digest: sha256:5a7a8fdc52f48911c3b59dfa3ea757ad5386ecc585c664f35ddce1d17bc1966f
      DiffID: sha256:b56fb45dbc09c27803605502b2c6d859670ce70d16087217d901e1755f68f118
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2025-0167
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: When asked to use a `.netrc` file for credentials **and** to follow HT ...
    Description: |-
      When asked to use a `.netrc` file for credentials **and** to follow HTTP
      redirects, curl could leak the password used for the first host to the
      followed-to host under certain circumstances.

      This flaw only manifests itself if the netrc file has a `default` entry that
      omits both login and password. A rare circumstance.
    Severity: LOW
    VendorSeverity:
      ubuntu: 1
    References:
    - https://curl.se/docs/CVE-2025-0167.html
    - https://curl.se/docs/CVE-2025-0167.json
    - https://hackerone.com/reports/2917232
    - https://www.cve.org/CVERecord?id=CVE-2025-0167
    PublishedDate: '2025-02-05T10:15:22.71Z'
    LastModifiedDate: '2025-02-06T15:15:16.967Z'
  - VulnerabilityID: CVE-2025-0665
    PkgID: curl@8.11.1-r1
    PkgName: curl
    PkgIdentifier:
      PURL: pkg:apk/alpine/curl@8.11.1-r1?arch=x86_64&distro=3.21.2
      UID: 6c52f830beb86792
    InstalledVersion: 8.11.1-r1
    FixedVersion: 8.12.0-r0
    Status: fixed
    Layer:
      Digest: sha256:5a7a8fdc52f48911c3b59dfa3ea757ad5386ecc585c664f35ddce1d17bc1966f
      DiffID: sha256:b56fb45dbc09c27803605502b2c6d859670ce70d16087217d901e1755f68f118
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2025-0665
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: libcurl would wrongly close the same eventfd file descriptor twice whe ...
    Description: |-
      libcurl would wrongly close the same eventfd file descriptor twice when taking
      down a connection channel after having completed a threaded name resolve.
    Severity: UNKNOWN
    CweIDs:
    - CWE-1341
    References:
    - http://www.openwall.com/lists/oss-security/2025/02/05/2
    - http://www.openwall.com/lists/oss-security/2025/02/05/5
    - https://curl.se/docs/CVE-2025-0665.html
    - https://curl.se/docs/CVE-2025-0665.json
    - https://hackerone.com/reports/2954286
    PublishedDate: '2025-02-05T10:15:22.857Z'
    LastModifiedDate: '2025-02-05T20:15:45.31Z'
  - VulnerabilityID: CVE-2025-0725
    PkgID: libcurl@8.11.1-r1
    PkgName: libcurl
    PkgIdentifier:
      PURL: pkg:apk/alpine/libcurl@8.11.1-r1?arch=x86_64&distro=3.21.2
      UID: e9ad8e93751a035c
    InstalledVersion: 8.11.1-r1
    FixedVersion: 8.12.0-r0
    Status: fixed
    Layer:
      Digest: sha256:5a7a8fdc52f48911c3b59dfa3ea757ad5386ecc585c664f35ddce1d17bc1966f
      DiffID: sha256:b56fb45dbc09c27803605502b2c6d859670ce70d16087217d901e1755f68f118
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2025-0725
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'libcurl: Buffer Overflow in libcurl via zlib Integer Overflow'
    Description: |-
      When libcurl is asked to perform automatic gzip decompression of
      content-encoded HTTP responses with the `CURLOPT_ACCEPT_ENCODING` option,
      **using zlib 1.2.0.3 or older**, an attacker-controlled integer overflow would
      make libcurl perform a buffer overflow.
    Severity: MEDIUM
    VendorSeverity:
      redhat: 1
    CVSS:
      redhat:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L
        V3Score: 4
    References:
    - http://www.openwall.com/lists/oss-security/2025/02/05/3
    - http://www.openwall.com/lists/oss-security/2025/02/06/2
    - http://www.openwall.com/lists/oss-security/2025/02/06/4
    - https://access.redhat.com/security/cve/CVE-2025-0725
    - https://curl.se/docs/CVE-2025-0725.html
    - https://curl.se/docs/CVE-2025-0725.json
    - https://hackerone.com/reports/2956023
    - https://nvd.nist.gov/vuln/detail/CVE-2025-0725
    - https://www.cve.org/CVERecord?id=CVE-2025-0725
    PublishedDate: '2025-02-05T10:15:22.98Z'
    LastModifiedDate: '2025-02-06T19:15:19.733Z'
  - VulnerabilityID: CVE-2025-0167
    PkgID: libcurl@8.11.1-r1
    PkgName: libcurl
    PkgIdentifier:
      PURL: pkg:apk/alpine/libcurl@8.11.1-r1?arch=x86_64&distro=3.21.2
      UID: e9ad8e93751a035c
    InstalledVersion: 8.11.1-r1
    FixedVersion: 8.12.0-r0
    Status: fixed
    Layer:
      Digest: sha256:5a7a8fdc52f48911c3b59dfa3ea757ad5386ecc585c664f35ddce1d17bc1966f
      DiffID: sha256:b56fb45dbc09c27803605502b2c6d859670ce70d16087217d901e1755f68f118
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2025-0167
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: When asked to use a `.netrc` file for credentials **and** to follow HT ...
    Description: |-
      When asked to use a `.netrc` file for credentials **and** to follow HTTP
      redirects, curl could leak the password used for the first host to the
      followed-to host under certain circumstances.

      This flaw only manifests itself if the netrc file has a `default` entry that
      omits both login and password. A rare circumstance.
    Severity: LOW
    VendorSeverity:
      ubuntu: 1
    References:
    - https://curl.se/docs/CVE-2025-0167.html
    - https://curl.se/docs/CVE-2025-0167.json
    - https://hackerone.com/reports/2917232
    - https://www.cve.org/CVERecord?id=CVE-2025-0167
    PublishedDate: '2025-02-05T10:15:22.71Z'
    LastModifiedDate: '2025-02-06T15:15:16.967Z'
  - VulnerabilityID: CVE-2025-0665
    PkgID: libcurl@8.11.1-r1
    PkgName: libcurl
    PkgIdentifier:
      PURL: pkg:apk/alpine/libcurl@8.11.1-r1?arch=x86_64&distro=3.21.2
      UID: e9ad8e93751a035c
    InstalledVersion: 8.11.1-r1
    FixedVersion: 8.12.0-r0
    Status: fixed
    Layer:
      Digest: sha256:5a7a8fdc52f48911c3b59dfa3ea757ad5386ecc585c664f35ddce1d17bc1966f
      DiffID: sha256:b56fb45dbc09c27803605502b2c6d859670ce70d16087217d901e1755f68f118
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2025-0665
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: libcurl would wrongly close the same eventfd file descriptor twice whe ...
    Description: |-
      libcurl would wrongly close the same eventfd file descriptor twice when taking
      down a connection channel after having completed a threaded name resolve.
    Severity: UNKNOWN
    CweIDs:
    - CWE-1341
    References:
    - http://www.openwall.com/lists/oss-security/2025/02/05/2
    - http://www.openwall.com/lists/oss-security/2025/02/05/5
    - https://curl.se/docs/CVE-2025-0665.html
    - https://curl.se/docs/CVE-2025-0665.json
    - https://hackerone.com/reports/2954286
    PublishedDate: '2025-02-05T10:15:22.857Z'
    LastModifiedDate: '2025-02-05T20:15:45.31Z'
  - VulnerabilityID: CVE-2025-26519
    PkgID: musl@1.2.5-r8
    PkgName: musl
    PkgIdentifier:
      PURL: pkg:apk/alpine/musl@1.2.5-r8?arch=x86_64&distro=3.21.2
      UID: 936f1fd92822db90
    InstalledVersion: 1.2.5-r8
    FixedVersion: 1.2.5-r9
    Status: fixed
    Layer:
      Digest: sha256:5a7a8fdc52f48911c3b59dfa3ea757ad5386ecc585c664f35ddce1d17bc1966f
      DiffID: sha256:b56fb45dbc09c27803605502b2c6d859670ce70d16087217d901e1755f68f118
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Severity: UNKNOWN
  - VulnerabilityID: CVE-2025-26519
    PkgID: musl-utils@1.2.5-r8
    PkgName: musl-utils
    PkgIdentifier:
      PURL: pkg:apk/alpine/musl-utils@1.2.5-r8?arch=x86_64&distro=3.21.2
      UID: f25fd050ed07b9ad
    InstalledVersion: 1.2.5-r8
    FixedVersion: 1.2.5-r9
    Status: fixed
    Layer:
      Digest: sha256:5a7a8fdc52f48911c3b59dfa3ea757ad5386ecc585c664f35ddce1d17bc1966f
      DiffID: sha256:b56fb45dbc09c27803605502b2c6d859670ce70d16087217d901e1755f68f118
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Severity: UNKNOWN
- Target: Java
  Class: lang-pkgs
  Type: jar
