- Target: openaf/ojobrt:nightly (alpine 3.18.2)
  Class: os-pkgs
  Type: alpine
- Target: Java
  Class: lang-pkgs
  Type: jar
  Vulnerabilities:
  - VulnerabilityID: CVE-2023-2976
    PkgName: com.google.guava:guava
    PkgPath: openaf/S3/minio-8.5.4-all.jar
    InstalledVersion: 32.0.0-jre
    FixedVersion: 32.0.1-android
    Layer:
      Digest: sha256:65b0c18db87b1dc71e288f1d795ddf31b3764be490bd17d8881c24031408c324
      DiffID: sha256:f1a63ad7e3047f01023a8a4ed5419e1c38002dcafef1c069895a586ea0cca586
    SeveritySource: nvd
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2023-2976
    DataSource:
      ID: glad
      Name: GitLab Advisory Database Community
      URL: https://gitlab.com/gitlab-org/advisories-community
    Title: insecure temporary directory creation
    Description: |+
      Use of Java's default temporary directory for file creation in `FileBackedOutputStream` in Google Guava versions 1.0 to 31.1 on Unix systems and Android Ice Cream Sandwich allows other users and apps on the machine with access to the default Java temporary directory to be able to access the files created by the class.

      Even though the security vulnerability is fixed in version 32.0.0, we recommend using version 32.0.1 as version 32.0.0 breaks some functionality under Windows.

    Severity: HIGH
    CweIDs:
    - CWE-552
    CVSS:
      ghsa:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N
        V3Score: 5.5
      nvd:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:N
        V3Score: 7.1
      redhat:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:L/I:L/A:N
        V3Score: 4.4
    References:
    - https://access.redhat.com/security/cve/CVE-2023-2976
    - https://github.com/advisories/GHSA-7g45-4rm6-3mm3
    - https://github.com/google/guava/commit/feb83a1c8fd2e7670b244d5afd23cba5aca43284
    - https://github.com/google/guava/issues/2575
    - https://github.com/google/guava/issues/6532
    - https://github.com/google/guava/releases/tag/v32.0.0
    - https://nvd.nist.gov/vuln/detail/CVE-2023-2976
    - https://www.cve.org/CVERecord?id=CVE-2023-2976
    PublishedDate: '2023-06-14T18:15:00Z'
    LastModifiedDate: '2023-06-29T18:22:00Z'
