author: Nuno Aguiar
scripts:
  preerase: ''
  posterase: ''
  preinstall: ''
  postinstall: ''
keywords:
  - openaf
  - ojob
  - ojobc
  - openaf-console
  - docker
bugs:
  url: 'https://github.com/OpenAF/openaf-dockers/issues'
repository:
  type: http
  url: 'https://openaf.io/opacks/openaf-dockers.opack'
description: Main OpenAF docker builds source
name: openaf-dockers
main: ''
mainJob: ''
license: 'https://github.com/OpenAF/openaf-dockers/blob/master/LICENSE'
version: '20190316'
dependencies: null
files:
  - openaf-console/Dockerfile
  - openaf-console/README.md
  - openaf-console/entrypoint.sh
  - oJob/Dockerfile
  - oJob/README.md
  - oJob/entrypoint.sh
  - oJob/main.yaml
  - oJobC/Dockerfile
  - oJobC/README.md
  - oJobC/entrypoint.sh
  - oJobC/main.yaml
  - .package.yaml
  - LICENSE
  - README.md
  - openaf/Dockerfile
  - openaf/README.md
  - openaf/entrypoint.sh
  - openaf/installOPacks.js
filesHash:
  openaf-console/Dockerfile: 853e6beeb6ed7b948c4f0e9617beaf01ed30eaee
  openaf-console/README.md: 4e62401469fa378e04e39e0b802c1406ae4db976
  openaf-console/entrypoint.sh: c1f52eebe07efbb7329048c66208c9b7aa9bc13a
  oJob/Dockerfile: 06c9df19ab26eb744977a5468672049eb8ec4206
  oJob/README.md: ea76b2e5b449aa26f20e5d9b9e65fd561ce2bce3
  oJob/entrypoint.sh: e5e3097047fcf035bdbe1e07405a4f2244457e49
  oJob/main.yaml: 8603425f1cacdc847bff1c7c474b9db3548be81e
  oJobC/Dockerfile: 527831946d47e45690785c34d146b56edfa2f585
  oJobC/README.md: 34ef1c4872425f38f33e8cdc631aeeeffe0fd465
  oJobC/entrypoint.sh: e5e3097047fcf035bdbe1e07405a4f2244457e49
  oJobC/main.yaml: 8603425f1cacdc847bff1c7c474b9db3548be81e
  LICENSE: 7df059597099bb7dcf25d2a9aedfaf4465f72d8d
  README.md: 08d0e96349bbfc3760107949e271e27cb5d9ca25
  openaf/Dockerfile: 8bbd9e74361fe124f5358185d6ddf4effbe53b4d
  openaf/README.md: 07368ea69b6a24d4bbda4046606d56e913f113cf
  openaf/entrypoint.sh: fab2355fe7f7d8b20adfcfa924c07320437ba09c
  openaf/installOPacks.js: 97b4fe2b41d9c94db2a51609bab3871115fe463e
