name: Scan Images

on:
  workflow_dispatch:
  schedule:
    - cron: '27 5 * * 5'

jobs:
  Scan-Images:
    permissions:
      contents: write
      pull-requests: write
      
    runs-on: ubuntu-latest
    name: Scan images
    steps:
    - name: Cache OpenAF runtime
      uses: actions/cache@v3
      with:
        key : oaf-t8
        path: /tmp/oaf
        
    - name: Retrieve trivy java database
      uses: openaf/ojob-action@v5
      with:
        ojob: 'ojob.io/sec/trivy'
        args: 'dockerOptions="-v trivy-db:/root/.cache/trivy" options="image --download-java-db-only"'
      
    - name: Retrieve trivy database
      uses: openaf/ojob-action@v5
      with:
        ojob: 'ojob.io/sec/trivy'
        args: 'dockerOptions="-v trivy-db:/root/.cache/trivy" options="image --download-db-only"'

    - name: Store the trivy databases in cache
      run : |
        docker run --rm -v trivy-db:/volume -v /tmp/oaf:/backup busybox tar czf /backup/trivy-db.tgz -C /volume .